<a href="https://colab.research.google.com/github/LucasQCosta/Machine_Learning---Alura/blob/main/Classifica%C3%A7%C3%A3o_por_tr%C3%A1s_dos_panos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/LucasQCosta/Machine_Learning---Alura.git

## Importando Dados

In [ ]:
import pandas as pd

In [ ]:
dados = pd.read_csv('/content/Machine_Learning---Alura/2 - Classificação por trás dos panos/dados/Customer-Churn.csv')

In [ ]:
dados.head()

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo  \
0            0     Sim         Nao                1          Nao   
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   
3            0     Nao         Nao               45          Nao   
4            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline  \
0    SemServicoTelefonico               DSL             Nao          Sim   
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   
3    SemServicoTelefonico               DSL             Sim          Nao   
4                     Nao       FibraOptica             Nao          Nao   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato  \
0                 Nao            Nao     Nao               Nao    Mensalmente   
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   
3                 Sim            Sim     Nao               Nao          UmAno   
4                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim  
3             Nao    DebitoEmConta        42.30   Nao  
4             Sim    ChequeDigital        70.70   Sim

## Treinando os modelos

### Transformar dados categóricos em dados numéricos

In [ ]:
transform_dic = {'Sim': 1,
                 'Nao': 0}
dadosmodificados = dados[['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn']].replace(transform_dic)
dadosmodificados.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0        1            0             0                1      0
1        0            0             1                0      0
2        0            0             1                1      1
3        0            0             0                0      0
4        0            0             1                1      1

In [ ]:
##### Outra forma de fazer
dummies_dados = pd.get_dummies(dados.drop(['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn'], axis=1))
dados_final = pd.concat([dadosmodificados, dummies_dados], axis=1)
dados_final.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   
3               45        42.30                            0   
4                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  ...  StreamingDeFilmes_Nao  \
0                                             1  ...                      1   
1                                             0  ...                      1   
2                                             0  ...                      1   
3                                             1  ...                      1   
4                                             0  ...                      1   

   StreamingDeFilmes_SemServicoDeInternet  StreamingDeFilmes_Sim  \
0                                       0                      0   
1                                       0                      0   
2                                       0                      0   
3                                       0                      0   
4                                       0                      0   

   TipoDeContrato_DoisAnos  TipoDeContrato_Mensalmente  TipoDeContrato_UmAno  \
0                        0                           1                     0   
1                        0                           0                     1   
2                        0                           1                     0   
3                        0                           0                     1   
4                        0                           1                     0   

   FormaDePagamento_CartaoDeCredito  FormaDePagamento_ChequeDigital  \
0                                 0                               1   
1                                 0                               0   
2                                 0                               0   
3                                 0                               0   
4                                 0                               1   

   FormaDePagamento_ChequePapel  FormaDePagamento_DebitoEmConta  
0                             0                               0  
1                             1                               0  
2                             1                               0  
3                             0                               1  
4                             0                               0  

[5 rows x 39 columns]

### Modelo KNN (K-Nearest Neighbors)

- Pode ser usado tanto com classificação quanto com regressão.

#### Normalizando os dados

In [ ]:
# Divisão dos dados (Input/ Output)
input = dados_final.drop('Churn', axis=1) # Valores de entrada
output = dados_final['Churn'] # Valores desejados de retorno

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
# Deixar todos os valores na mesma escala, ou seja, normalizando o input
norm = StandardScaler()

input_normalizado = norm.fit_transform(input)
input_normalizado[0]

array([ 1.03453023, -0.65401193, -3.05401039,  0.8297975 , -0.43991649,
       -1.27744458, -1.16032292, -0.96332984,  3.05401039, -0.85417615,
        1.38171215, -0.88565976, -0.52592737,  1.00669571, -0.52592737,
       -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
       -0.52592737, -0.72396752,  1.0138687 , -0.52592737, -0.63943864,
        1.2273572 , -0.52592737, -0.79013171,  1.23648892, -0.52592737,
       -0.79607014, -0.56297505,  0.90418382, -0.51424938, -0.52504733,
        1.40641839, -0.54480692, -0.5298852 ])

#### Implementando o modelo

In [ ]:
from sklearn.model_selection import train_test_split # Bilioteca que realiza a divisão dos dados em treino e teste

In [ ]:
# Variáveis para armazenar esse valores
x_treino, x_teste, y_treino, y_teste = train_test_split(input_normalizado, output, test_size = 0.3, random_state=123)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier(metric='euclidean')

In [ ]:
knn.fit(x_treino, y_treino)

KNeighborsClassifier(metric='euclidean')

In [ ]:
predito_knn = knn.predict(x_teste)

In [ ]:
predito_knn

array([1, 0, 0, ..., 0, 0, 0])

### Método Probabilístico

In [ ]:
import numpy as np
np.median(x_treino)

-0.5259273725834717

In [ ]:
from sklearn.naive_bayes import BernoulliNB

In [ ]:
bnb = BernoulliNB(binarize=0.53) # Define que acima de -0.44 -> 1 e menor o valor é zero

In [ ]:
bnb.fit(x_treino, y_treino)

BernoulliNB(binarize=0.53)

In [ ]:
predito_bnb = bnb.predict(x_teste)
predito_bnb

array([1, 0, 0, ..., 0, 1, 0])

### Árvore de Decisão

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dtc = DecisionTreeClassifier(criterion='entropy', random_state=42)

In [ ]:
dtc.fit(x_treino, y_treino)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [ ]:
dtc.feature_importances_

array([0.03168742, 0.01862901, 0.00064085, 0.02675693, 0.0208788 ,
       0.2056003 , 0.29546501, 0.0061786 , 0.00273035, 0.00747536,
       0.        , 0.04908356, 0.        , 0.01609395, 0.        ,
       0.00722833, 0.01220706, 0.        , 0.01248286, 0.01138295,
       0.0006673 , 0.0095669 , 0.01841631, 0.        , 0.00650511,
       0.00385849, 0.        , 0.00666929, 0.00517146, 0.        ,
       0.00665371, 0.00473251, 0.15803541, 0.00348686, 0.01414378,
       0.01601964, 0.01064163, 0.01091026])

In [ ]:
predito_dtc = dtc.predict(x_teste)
predito_dtc

array([1, 0, 0, ..., 1, 0, 0])

## Como escolher o melhor modelo:

### Matrix Confusão

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
print(confusion_matrix(y_teste, predito_knn))

[[1305  218]
 [ 317  273]]


In [ ]:
print(confusion_matrix(y_teste, predito_bnb))

[[1058  465]
 [ 120  470]]


In [ ]:
print(confusion_matrix(y_teste, predito_dtc))

[[1249  274]
 [ 290  300]]


### Acurácia

$Accuracy = \frac{TP + TN}{TP + TN + FP + FN} = \frac{N° Acertos}{N° Elementos}$

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print(accuracy_score(y_teste, predito_knn))

0.7468054898248935


In [ ]:
print(accuracy_score(y_teste, predito_bnb))

0.7231424514907714


In [ ]:
print(accuracy_score(y_teste, predito_dtc))

0.7330809275911027


### Precision

Quantos verdadeiros positivos foram classificados de forma correta.

$Precision = \frac{TP}{TP + FP}$

In [ ]:
from sklearn.metrics import precision_score

In [ ]:
print(precision_score(y_teste, predito_knn))

0.5560081466395111


In [ ]:
print(precision_score(y_teste, predito_bnb))

0.5026737967914439


In [ ]:
print(precision_score(y_teste, predito_dtc))

0.5226480836236934


### Recall

Busca medir o quão bom o modelo é em medir o verdadeiro positivo (TP)

$Recall = \frac{TP}{TP + FN}$

In [ ]:
from sklearn.metrics import recall_score

In [ ]:
print(recall_score(y_teste, predito_knn))

0.46271186440677964


In [ ]:
print(recall_score(y_teste, predito_bnb))

0.7966101694915254


In [ ]:
print(recall_score(y_teste, predito_dtc))

0.5084745762711864


## Qual modelos escolher melhor?

- Melhor utilizar a precision, pois para o objetivo do curso é reduzir o número de pessoas que estão deixando a empresa.

- Então, olhando esse parametro o melhor modelo é o knn, que apresentou uma precision de 55,60%.